"""Declarative tier configurations for the synthetic fixture generator."""

from dataclasses import dataclass, field


@dataclass(frozen=True)
class TierConfig:
    name: str                                  # "A1", "B2", etc.
    classes: list[str]                         # ["Movie"], etc.
    sources_per_class: dict[str, list[str]]    # {"Movie": ["imdb_movies"]}
    base_volumes: dict[str, int]               # {"Movie": 50}
    seeded_categories: list[int]               # which EDGE-CASES.md categories
    seed: int                                  # deterministic random seed


A1 = TierConfig(
    name="A1",
    classes=["Movie"],
    sources_per_class={"Movie": ["imdb_movies"]},
    base_volumes={"Movie": 50},
    seeded_categories=[1, 2, 3, 9, 11, 12, 14, 15],
    seed=20250505_1,  # A1 seed
)

# Stubs — fixture data not generated by this dispatch:
B2 = TierConfig(
    name="B2",
    classes=["Movie", "Person", "Credit"],
    sources_per_class={
        "Movie": ["imdb_movies", "tmdb_movies", "wikidata_movies"],
        "Person": ["imdb_persons", "tmdb_persons", "wikidata_persons"],
        "Credit": ["imdb_credits", "tmdb_credits", "wikidata_credits"],
    },
    base_volumes={"Movie": 50, "Person": 100, "Credit": 200},
    seeded_categories=list(range(1, 16)),
    seed=20250505_2,  # B2 seed
)

C2 = TierConfig(
    name="C2",
    classes=[
        "Title", "Movie", "Series", "Episode", "Game",
        "Person", "Credit", "Identifier", "Studio", "Award", "Country",
    ],
    sources_per_class={
        "Movie": ["imdb_movies", "tmdb_movies"],
        "Series": ["imdb_series", "tmdb_series"],
        "Episode": ["imdb_episodes", "tmdb_episodes"],
        "Game": ["igdb_games", "steam_games"],
        "Person": ["imdb_persons", "tmdb_persons"],
        "Credit": ["imdb_credits", "tmdb_credits"],
        "Identifier": ["imdb_identifiers"],
        "Studio": ["imdb_studios"],
        "Award": ["imdb_awards"],
        "Country": ["iso_countries"],
    },
    base_volumes={
        "Movie": 50, "Series": 30, "Episode": 200, "Game": 20,
        "Person": 100, "Credit": 300, "Identifier": 500,
        "Studio": 20, "Award": 50, "Country": 50,
    },
    seeded_categories=list(range(1, 16)),
    seed=20250505_3,  # C2 seed
)
